### ISSUE TITLE
Cleanup setting slip for prescribed slip

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#106]
When updating the slip auxiliary subfield for faults, we need to sum the slip across all earthquake ruptures and then set that value in the fault auxiliary subfield. Right now, slip is the only subfield in the fault auxiliary subfield, so we can simple zero the fault auxiliary subfield before looping over the earthquake ruptures. If we have fault orientation or other subfields in the auxiliary subfield this would zero them out.

**Comment by knepley** [comment]
We could run the first project with INSERT and the rest with ADD. Would that zero out the values? Otherwise, we can just loop over one field with the Section and set it to zero.

**Comment by baagaard-usgs** [comment]
I think operating on sections to get the slip contribution from all of the ruptures with one final project is going to be the simplest and most efficient way to resolve this.
