### ISSUE TITLE
Check (and report) bounding box of domain upon importing mesh

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#107]
Check (and report via journal info) the bounding box of the domain upon importing the mesh. The check is that the volume of the domain is greater than zero. We should do this immediately after importing the mesh (when we check the topology).

The check would alert users who import a 2-D mesh that was not in an x-y coordinate system. For example, generating a mesh in CUBIT/Trelis that is in the xz coordinate system and exporting as 2-D results in all y coordinates equal to 0.

**Comment by baagaard-usgs** [comment]
@knepley Can I use `DMDAGetBoundingBox()` or do you need to create a new `DMGetBoundingBox()` function?

**Comment by knepley** [comment]
I compute it internally but never exposed it. I will fix it.

**Comment by baagaard-usgs** [comment]
Use [DMGetBoundingBox()](https://www.mcs.anl.gov/petsc/petsc-master/docs/manualpages/DM/DMGetBoundingBox.html).
