### ISSUE TITLE
Fault orientation inconsistent with sense of slip (mesh dependent).

### ISSUE THREAD

**Issue by baagaard** [geodynamics/pylith#11]
When choosing the orientation of the fault mesh (which controls the fault normal direction), it is possible for the submesh to be oriented inconsistently with the cohesive cells. This appears to happen on occasion (quite infrequently) when running in parallel.

Reported by Romain Jolivet.

**Comment by baagaard-usgs** [comment]
Finally fixed in PETSc https://bitbucket.org/petsc/petsc/commits/9beae1230f31db2bcf195e1162efd9c0118033fc.

Will show up in PyLith v2.2.0 release.
