### ISSUE TITLE
why this "spatialdata" can't be installed by command "pip install spatialdata"?

### ISSUE THREAD

**Issue by gaoxinlei** [geodynamics/pylith#118]
https://github.com/geodynamics/pylith/blob/f74060b7b19d7e90abf8597bbe9250c96593c0ad/pylith/tests/Fault.py#L25

**Comment by gaoxinlei** [comment]
This problem confused me a lot, I can't install "spatialdata" through "pip" tool, nor search related information from stackoverflow, How can I install it? anyone could help us? @baagaard  @spikebike

**Comment by knepley** [comment]
spatialdata is part of the PyLith install and is not installed by pip. Did you install by downloading the binary install?

**Comment by gaoxinlei** [comment]
Hi @knepley  
Thanks.
Actually I just cloned pylith's code and try to run some unit tests for better understanding, We installed it by docker several days ago.
So how you tested your code ? it seems for test cases which depends on packages like "spatialdata" must build pylith first.

BR

**Comment by knepley** [comment]
PyLith, like many pieces of software, has package dependencies. The build process is described in the manual, and there is also a binary installation which we recommend.
