### ISSUE TITLE
P3, Q3, P4, and Q4 discretizations fail MMS tests

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#121]
Simulations with P3, Q3, P4, and Q4 discretizations are failing the MMS tests.

## Test Case

```
cd mmstests/elasticity
make check
```

The problem appears to be in the indexing of the solution, because the solution being passed in to the residual kernel does not agree with the expected solution for the coordinates. From https://github.com/geodynamics/pylith/issues/72#issuecomment-492023234:

Solution for uniform strain

```python
>>> def disp(x, y):
    exx = 0.1
    eyy = 0.25
    exy = 0.3
    disp_x = exx*x + exy*y
    disp_y = exy*x + eyy*y
    return (disp_x, disp_y)
```

Solution and coordinates in kernel for case when solution matches coordinates:

```
Thread 1 "test_isotropicl" hit Breakpoint 2, pylith::fekernels::IsotropicLinearElasticityPlaneStrain::g1v (dim=2, numS=1, numA=3, sOff=0x55555617a6c0, sOff_x=0x55555617ad20, s=0x555556187bb0, s_t=0x0, 
    s_x=0x55555618d830, aOff=0x555555dca9f0, aOff_x=0x555555dbc190, a=0x555555b73aa0, a_t=0x0, a_x=0x555555b76360, t=0, x=0x55555618dea0, numConstants=0, constants=0x0, g1=0x55555618e500)
    at /home/brad/src/cig/pylith/libsrc/pylith/fekernels/IsotropicLinearElasticity.cc:61
61	    assert(_dim == dim);
(gdb) p x[0]@2
$1 = {-0.86906601088997104, -0.88579160777096477}
(gdb) p s[0]@2
$2 = {-0.35264408342028686, -0.48216770520973284}
```

**Comment by knepley** [comment]
@baagaard-usgs I believe it is now fixed. I pushed to knepley/pylith.

The problem was the initial guess. Projection was broken for high order if components were being specified.

**Comment by baagaard-usgs** [comment]
Fix verified. MMS tests for elasticity and incomrpessible elasticity all pass (P1-P3, Q1-Q3).
