### ISSUE TITLE
Reordered mesh has different closure sizes for coordinates

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#124]
After applying reverse Cuthill-McKee reordering to a tet or hex mesh with a fault, the mesh has different closure sizes for the vertex coordinates.

[Closure size at Line 151 in TestReverseCuthillMcKee.cc](https://github.com/geodynamics/pylith/blob/baagaard/reorganize-examples/unittests/libtests/topology/TestReverseCuthillMcKee.cc#L151)

## Reproduce

**PyLith branch**: baagaard/reorganize-examples

```
cd unittests/libtests/topology
make check
```

```
!!!FAILURES!!!
Test Results:
Run:  99   Failures: 2   Errors: 0

1) test: pylith::topology::TestReverseCuthillMcKee_Tet_Fault::testReorder (F) line: 151 /Volumes/Users/baagaard/src/cig/pylith/unittests/libtests/topology/TestReverseCuthillMcKee.cc
equality assertion failed
- Expected: 72
- Actual  : 66


2) test: pylith::topology::TestReverseCuthillMcKee_Hex_Fault::testReorder (F) line: 151 /Volumes/Users/baagaard/src/cig/pylith/unittests/libtests/topology/TestReverseCuthillMcKee.cc
equality assertion failed
- Expected: 153
- Actual  : 144
```

[pylith::topology::TestReverseCuthillMcKee_Hex_Fault::testReorder (F) line: 151](https://github.com/geodynamics/pylith/blob/baagaard/reorganize-examples/unittests/libtests/topology/TestReverseCuthillMcKee.cc#L151)

```
CPPUNIT_ASSERT_EQUAL(totalClosureSizeOrig, totalClosureSizeReorder);

**Comment by knepley** [comment]
@baagaard This should now be fixed.

It turned out to have nothing at all to do with reordering. Your test just luckily caught a difficult memory bug. The closure for hybrid cells was being calculated incorrectly.

**Comment by baagaard-usgs** [comment]
Verified update to PETSc knepley/pylith resolves the issue.
