### ISSUE TITLE
Applying Dirichlet and Neumann BC on same domain 

### ISSUE THREAD

**Issue by kimtaeho07** [geodynamics/pylith#129]
Does Pylith currently support applying both Dirichlet and Neumann BC on the same domain (in orthgonal directions)?  For example, to an edge of a 2-D rectangle, enforcing a specific normal force and tangential displacement-rate?  I am currently running into the problem that the software asks that I specify both traction-normal and traction-shear values for any Neumann BC.

**Comment by baagaard-usgs** [comment]
Yes, you can combine Dirichlet and Neumann boundary conditions. The Dirichlet boundary condition specifies constraints on the degrees of freedom aligned with the coordinate axes (x, y, z) whereas the Neumann boundary condition specifies the traction components in the normal/tangential degrees of freedom.

This means that when you want to use a combination of Dirichlet and Neumann boundary conditions, you should constrain only a subset of the degrees of freedom for the Dirichlet boundary condition, and you need to supply all traction components for the Neumann boundary condition. You can supply zero values for traction components that you do not wish to include.

**Comment by kimtaeho07** [comment]
I see.  Thank you very much for your help.
