### ISSUE TITLE
Error while setting solution output with refiner = pylith.topology.RefineUniform

### ISSUE THREAD

**Issue by demiangomez** [geodynamics/pylith#14]
While running one of the benchmark problems (reverseslip_tet4_0250m) with refiner = pylith.topology.RefineUniform, the following error is reported while setting up solution output:

HDF5-DIAG: Error detected in HDF5 (1.8.8) MPI-process 0:
  #000: ../../hdf5-1.8.8/src/H5Dio.c line 266 in H5Dwrite(): can't write data
    major: Dataset
    minor: Write failed
  #001: ../../hdf5-1.8.8/src/H5Dio.c line 671 in H5D_write(): can't write data
    major: Dataset
    minor: Write failed

See attached file for complete stdout and stderr. This problem occurred both in a cluster and a desktop computer. Pylith version 2.1.0 (Linux ~ x86_64 (64 bit)) binaries downloaded from the CIG website). Benchmark runs correctly without setting refiner = pylith.topology.RefineUniform

[output_i.txt](https://github.com/geodynamics/pylith/files/119526/output_i.txt)

**Comment by knepley** [comment]
On Fri, Feb 5, 2016 at 11:09 AM, demiangomez <notifications@github.com>
wrote:

> While running one of the benchmark problems (reverseslip_tet4_0250m) with
> refiner = pylithtopologyRefineUniform, the following error is reported
> while setting up solution output:
>
> HDF5-DIAG: Error detected in HDF5 (188) MPI-process 0:
> #000: //hdf5-188/src/H5Dioc line 266 in H5Dwrite(): can't write data
> major: Dataset
> minor: Write failed
> #1 <https://github.com/geodynamics/pylith/issues/1>:
> //hdf5-188/src/H5Dioc line 671 in H5D_write(): can't write data
> major: Dataset
> minor: Write failed
>
> See attached file for complete stdout and stderr This problem occurred
> both in a cluster and a desktop computer Pylith version 210 (Linux ~ x86_64
> (64 bit)) binaries downloaded from the CIG website) Benchmark runs
> correctly without setting refiner = pylithtopologyRefineUniform
>
We will look at this at our weekly code review on Tuesday.

  Thanks,

     Matt


> output_itxt
> <https://githubcom/geodynamics/pylith/files/119526/output_itxt>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/pylith/issues/14>.
>



-- 
What most experimenters take for granted before they begin their
experiments is infinitely more interesting than any results to which their
experiments lead.
-- Norbert Wiener

**Comment by baagaard** [comment]
The input/parameter files for that benchmark have not been updated to 
the current version of PyLith. All of the examples included in the 
PyLith source and binary distributions are always kept up to date, but 
we don't have the resources to keep all of the benchmark input files up 
to date. We would welcome help from the community in updating the 
benchmark input files.

Regards,
Brad

**Comment by demiangomez** [comment]
Hi Brad,

Sure, I can provide the files I'm using to run the benchmarks. However, the
reverse no gravity benchmark did not require any modifications. I can make
a contribution by verifying the rest of the benchmarks too. I'm also
working on another benchmark test (using a spherical mesh) that might be
interesting to add as either an example or benchmark once I figure it out.

Regards,
Demián

**Comment by baagaard-usgs** [comment]
See https://github.com/geodynamics/pylith_benchmarks/issues/1
