### ISSUE TITLE
Version 2.1.3 for Windows

### ISSUE THREAD

**Issue by baagaard** [geodynamics/pylith#19]
There is no binary that runs on Windows. The current workarounds are to use binary package for v2.1.0 or run the Linux binary via VirtualBox.

**Comment by baagaard** [comment]
Cygwin builds are proving to be very fragile and often require rebasing. Distributing cgwin+pylith does not seem to be a robust solution. We are investigating some alternative solutions:

* Native Windows build using the bash shell that might become available in Windows 10. http://insights.ubuntu.com/2016/03/30/ubuntu-on-windows-the-ubuntu-userspace-for-windows-developers/

* Lightweight Linux virtual machine using Docker. Use Docker to build and distribute a lightweight Linux virtual machine that includes PyLith and its dependencies. We would have to setup the virtual machine so that the native filesystem(s) could be mounted for read/write.

**Comment by baagaard-usgs** [comment]
The PyLith v2.1.4 release includes a Docker container, which is available on DockerHub https://hub.docker.com/r/geodynamics/pylith/.

**Comment by baagaard-usgs** [comment]
On Windows 10 Build 1607 and later, one can enable the "Windows Subsystem for Linux" and install "Ubuntu on Windows". This allows use of the Linux x86_64 binary within a bash shell. This approach is much easier and user friendly than using a Docker image or Virtual Machine. We will update the PyLith installation instructions to include this approach.

**Comment by baagaard-usgs** [comment]
Instructions are included in PyLith manual for the 2.2.1 release.
