### ISSUE TITLE
Generate citation information.

### ISSUE THREAD

**Issue by baagaard** [geodynamics/pylith#21]
Add ability to display information on how to cite PyLith.

**Comment by baagaard** [comment]
Should we include this as part of --version or add a --citation command line argument?

How do we include citation information for PETSc, HDF5, NetCDF, plugins, etc?

**Comment by knepley** [comment]
I have put in PETSc citation style information in a branch. I would put it
in --citation

   Matt

On Thu, Jun 23, 2016 at 3:09 PM, baagaard <notifications@github.com> wrote:

> Should we include this as part of --version or add a --citation command
> line argument?
>
> How do we include citation information for PETSc, HDF5, NetCDF, plugins,
> etc?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/geodynamics/pylith/issues/21#issuecomment-228200561>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAjoiZZBqpj5LfCWGpg7QGq2auuSnuR3ks5qOwQlgaJpZM4I9SZh>
> .
>



-- 
What most experimenters take for granted before they begin their
experiments is infinitely more interesting than any results to which their
experiments lead.
-- Norbert Wiener

**Comment by baagaard** [comment]
Added in https://github.com/geodynamics/pylith/commit/c560fe60a395340e9ad4789d8386774dc13f7479.
