### ISSUE TITLE
'axialtract.cfg' example on run is giving NaN stress and strain outputs

### ISSUE THREAD

**Issue by sharmaviven1** [geodynamics/pylith#288]
![Screenshot at 2021-05-26 15-44-37](https://user-images.githubusercontent.com/84876891/119728681-601f2800-be39-11eb-9dc8-f58e53df7f43.png)

The 'axialtract.cfg' example file from the 'twoquad4' folder is giving strange outputs. Its not giving any simulation errors but at the same time its not giving the right results as it should from the manual.

**Comment by baagaard-usgs** [comment]
Please provide more information. What is the output of `pylith --version` (this tells us what version you are using and how it was built)? What did you type on the command line to run the simulation?

**Comment by sharmaviven1** [comment]
Here is the terminal output to the cmd 'pylith --version'.
[version_terminal_out.txt](https://github.com/geodynamics/pylith/files/6554869/version_terminal_out.txt)

The simulation was run using 'pylith axialtract.cfg' cmd in the terminal after initiating the pylith environment. 
[simu_terminal_out.txt](https://github.com/geodynamics/pylith/files/6554873/simu_terminal_out.txt)

**Comment by baagaard-usgs** [comment]
Thanks for the updated report. The issue is that the solver settings are out of date.

The `[petsc]` section of `pylithapp.cfg` should be

```
[pylithapp.petsc]
malloc_dump =

# Preconditioner settings.
pc_type = asm
sub_pc_factor_shift_type = nonzero

# Convergence parameters.
ksp_rtol = 1.0e-10
ksp_atol = 1.0e-20
ksp_max_it = 100
ksp_gmres_restart = 50

# Linear solver monitoring options.
ksp_monitor = true
#ksp_view = true
ksp_converged_reason = true
ksp_error_if_not_converged = true
```

**Comment by sharmaviven1** [comment]
Yup it worked. Thanks for the help.
