### ISSUE TITLE
sphinx-build does not recognize pdf

### ISSUE THREAD

**Issue by ljhwang** [geodynamics/pylith#331]
When building the documentation for sphinx, build.sh recognizes epub but not pdf as valid:

% ./build.sh pdf
Running Sphinx v3.5.0

Sphinx error:
Builder name pdf not registered or available through entry point

**Comment by baagaard-usgs** [comment]
`pdf` is not one of the sphinx build targets. To generate a PDF file you need to use `latex` or use sphinx-build directly with `-M latexpdf`.

See https://www.sphinx-doc.org/en/master/man/sphinx-build.html.

**Comment by ljhwang** [comment]
Thanks.  

The Developer documentation will need to be updated.
