### ISSUE TITLE
Wrong logic in computing Jacobian and residuals for dynamic slip

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#369]
The logic for computing the Jacobian and residuals for dynamic slip appears to be wrong. Our DAE equation is associated with the Lagrange multiplier field and has contributions from the adjacent faces:

![fault_dae](https://user-images.githubusercontent.com/22621443/142274902-2bfe5d8b-ef7f-4339-87a6-a5a7547c968b.png)

`DMPlexComputeResidual_Hybrid_Internal()` and `DMPlexComputeJacobian_Hybrid_Internal()` seem to be assuming that all the contributions to the residual for the Lagrange multiplier field and all the contributions to the Jacobian for the blocks associated with the Lagrange multiplier "row" are coming from interface kernels.

See for example:
https://gitlab.com/petsc/petsc/-/blob/knepley/pylith/src/dm/impls/plex/plexfem.c#L5642

## Reproduce

**PETSc branch**: knepley/pylith
**PyLith branch**: baagaard/feature-prescribed-slip-dynamic (forced push)

```
make install
cd $SRC/tests/manual/2d/faults-dynamic
pylith step01_swave_prescribedslip.cfg
`

``

**Comment by baagaard-usgs** [comment]
@knepley  The problem appears to be getting the auxiliary fields for the two sides of the fault.

In `DMPlexGetHybridAuxFields()`, `locA` looks correct, but getting the values via `DMPlexVecGetClosure()` at plexfem.c line 3438 results in Na=0, so no values are copied. As a result, the auxiliary array, `a`, in the kernels holds uninitialized values like X.XXXXe-324.

Note: fp_trap seems to find an error well before where the error related to the fault integration is.

**Comment by knepley** [comment]
@baagaard-usgs Okay, it turns out I was doing what I thought was the right thing. I was asking for auxiliary values from the adjoining _faces_. However, the aux field only has values on the adjoining _cells_.  I think switching to cells is correct, and will try that now.

**Comment by knepley** [comment]
@baagaard-usgs Okay, I have a fix in knepley/feature-plex-multiple-hybrid. I think we need to get to this branch anyway, so could yo try that one?

**Comment by baagaard-usgs** [comment]
Looks like I will first need to fix the fault Jacobian MMS test with this branch. I have built this branch and will debug tonight.

**Comment by baagaard-usgs** [comment]
@knepley Now I get this error with the dynamic prescribed slip test:

```
Form keys for each side of a cohesive surface must be different (material-id, 2, 0)
--snip--
PETSC ERROR: #1 DMPlexComputeJacobian_Hybrid_Internal() at /Users/baagaard/software/unix/petsc-dev/src/dm/impls/plex/plexfem.c:5531
PETSC ERROR: #2 static void pylith::feassemble::_IntegratorInterface::computeJacobian(PetscMat, PetscMat, const pylith::feassemble::IntegratorInterface *, pylith::feassemble::Integrator::JacobianPart, const PylithReal, const PylithReal, const PylithReal, const pylith::topology::Field &, const pylith::topology::Field &)() at /Users/baagaard/src/cig/pylith/libsrc/pylith/feassemble/IntegratorInterface.cc:618
```

Is this what I should expect if I try to repeat a key in the hybrid integration?

Why do I get this error for the Jacobian and not the residual?

**Comment by knepley** [comment]
Yes, we cannot use repeated keys, because then we cannot distinguish one side from the other.

The residual was missing the check, and was computing the wrong thing, since the kernel computation would have been repeated on each side.

**Comment by baagaard-usgs** [comment]
@knepley determined that the multiplexing of fields on the negative and positive sides of the fault is not consistent. `PetscFEEvaluateFieldJets_Hybrid_Internal()` in `fe.c` loops over fields then sides of the fault. We want the loop to be over sides of the fault then fields, so that we have [displacement-, velocity-, displacement+, velocity+, Lagrange multiplier] coming into the pointwise functions.

## Test case

**PETSc branch**: `knepley/pylith`
**PyLith branch**: `baagaard/feature-prescribed-slip-dynamic` (forced push)

Build PETSc and PyLith.

```
cd tests/manual/2d/faults-dynamic
PETSC_OPTIONS="-dm_plex_print_fem=2 -snes_test_jacobian -snes_test_jacobian_view" pylith step01_swave_prescribedslip.cfg --journal.debug.integratorinterface >& log
```

Examine `log` for inconsistencies between coded and finite-difference Jacobians. Want to get zeros for rows 24-27. The code uses an approximate (diagonal) Jacobian for rows 0-23, so we expect differences there.

**Comment by knepley** [comment]
@baagaard-usgs Okay, I pushed some fixes to your branch and force pushed `knepley/feature-plex-multiple-hybrid`. It is almost correct. I think that these kernels are mismatched somehow:
```
(material-id, 2) (0, 2) (1) pylith::fekernels::IsotropicLinearElasticityPlaneStrain::f1l_pos
(material-id, 2) (0, 2) (0) pylith::fekernels::IsotropicLinearElasticityPlaneStrain::f1l_neg
(material-id, 2) (2, 0) (1) pylith::fekernels::IsotropicLinearElasticityPlaneStrain::Jf3lu_pos
(material-id, 2) (2, 0) (0) pylith::fekernels::IsotropicLinearElasticityPlaneStrain::Jf3lu_neg
```
I cannot find the bug however.

**Comment by knepley** [comment]
If I comment out those kernels, the Jacobian passes, but if they are in the (l, u) block does not match.

**Comment by baagaard-usgs** [comment]
@knepley The offsets for the gradient in the solution for the positive side of the fault appear to be wrong. The negative side offsets are 0 as expected. It looks like the offsets for the gradient of the solution on the positive side of the fault are the same as the offsets for the solution itself.

**Comment by baagaard-usgs** [comment]
`s`, `s_x`, and `s_t` for hybrid integration contain information in the following order: field 0 negative, field 0 positive, field 1 negative, field 1 positive, ...

The `sOff`, `sOff_x` are adjusted in PETSc to be appropriate for each side of the fault.

**Comment by baagaard-usgs** [comment]
@knepley Below is what I think we have for the layout. With interleaved values from the negative and positive sides of the fault, the values at a point for a given field are no longer from off[f] to off[f+1]. I don't know how you want to handle this.

```
Solution field indices
          disp     vel
neg.  0  1       4  5
pos.  2  3       6  7
cohesive edge    lagrange 8  9

Gradient of solution indices
         disp.         vel
neg. 0,1  2,3      8,9      10,11
pos. 4,5  6,7      12,13  14,15
cohesive edge     lagrange 16,17    18,19


offCohesive[0] = [0, 4, ?, ?]
offCohesive[1] = [2, 6, ?, ?]
offCohesive[2] = [?, ?, 8, 10]

offDerCohesive[0] = [0, 8, ?, ?]
offDerCohesive[1] = [4, 12, ?, ?]
offDerCohesive[2] = [?, ?, 16, 20]
```

**Comment by knepley** [comment]
@baagaard-usgs Okay, I think I finally have all the offsets correct. However, there are still errors in the Jacobian.

Size determination from off[f+1] - off[f] never works, because we ostensibly allow permuting fields. The kernel is intended to know the size as a function of the dimension. What kernel should I look at for this?

**Comment by baagaard-usgs** [comment]
The offsets look correct to me now. The kernels that appear to be causing the discrepancy in the Jacobian (code vs finite difference) are `pylith::fekernels::IsotropicLinearElasticityPlaneStrain::f1l_neg` and `pylith::fekernels::IsotropicLinearElasticityPlaneStrain::f1l_pos`. Somehow, we are getting coupling in the Jacobian between the Lagrange multiplier and velocity even though the residual kernel has just stress in it. Maybe I am missing a term in the Jacobian.

**Comment by baagaard-usgs** [comment]
@knepley I am getting non-zero strains (gradient in displacement) when the displacement is zero but the velocity is non-zero. In this case how am I supposed to be computing the Jacobian for a term that depends on stress?

**Comment by knepley** [comment]
I saw your new commit, but it looks like you did not have mine:
```
 128baagaard/feature-prescribed-slip-dynamic *$:/PETSc3/cig/pylith-git$ git diff a60436a25d4adc5b6e17c95f62338bd99d2bf81e
diff --git a/libsrc/pylith/materials/Elasticity.cc b/libsrc/pylith/materials/Elasticity.cc
index d0a438a83..8cb5f1d95 100644
--- a/libsrc/pylith/materials/Elasticity.cc
+++ b/libsrc/pylith/materials/Elasticity.cc
@@ -263,7 +263,7 @@ pylith::materials::Elasticity::getInterfaceKernelsResidual(const pylith::topolog
         case pylith::feassemble::IntegratorInterface::NEGATIVE_FACE:
             f0l = pylith::fekernels::Elasticity::f0l_neg;
             f0l_stress = _rheology->getInterfaceKernelResidualF0Neg(coordsys);
-            f1l_stress = _rheology->getInterfaceKernelResidualF1Neg(coordsys);
+            f1l_stress = NULL;//_rheology->getInterfaceKernelResidualF1Neg(coordsys);
             break;
         case pylith::feassemble::IntegratorInterface::POSITIVE_FACE:
             f0l = pylith::fekernels::Elasticity::f0l_pos;
@@ -317,7 +317,7 @@ pylith::materials::Elasticity::getInterfaceKernelsJacobian(const pylith::topolog
         switch (face) {
         case pylith::feassemble::IntegratorInterface::NEGATIVE_FACE:
             Jf1lu = _rheology->getInterfaceKernelJacobianF1Neg(coordsys);
-            Jf3lu = _rheology->getInterfaceKernelJacobianF3Neg(coordsys);
+            Jf3lu = NULL;//_rheology->getInterfaceKernelJacobianF3Neg(coordsys);
             Jf0ll = pylith::fekernels::Elasticity::Jf0ll_neg;
             break;
         case pylith::feassemble::IntegratorInterface::POSITIVE_FACE:
```

**Comment by baagaard-usgs** [comment]
I purposefully removed your commit. I believe we want that part of the Jacobian to be diagonal since those equations are solved explicitly. We can test adding that once we get the Lagrange multiplier rows matching to see if it makes a difference.

**Comment by baagaard-usgs** [comment]
Matt and Brad found a few bugs in the PETSc residual and Jacobian integration. I am closing this issue and will open another issue if there are additional problems.
