### ISSUE TITLE
PyLith v3.0.0 fix list

### ISSUE THREAD

**Issue by willic3** [geodynamics/pylith#454]
- [x] intro/quickstart.html: Need Quickstart info.
- [x] intro/release-notes.html: Wasn’t there a 2.2.2 release?
- [x] intro/development-plan.html: Version 3.1.0 should be June 2022 (I think)
- [x] user/intro/new.html: Gmsh in new features?
- [x] user/install/index.html: We may need to note issues using the Mac binary to install PyLith 2.x if using 12.3 or above (I think that’s the version).
- [x] user/governingeqns/elasticity-infstrain/bulk-rheologies/index.html: We need section for linear elasticity. This can include volumetric/deviatoric separation + Jacobian info used by other bulk rheologies.
- [x] user/governingeqns/elasticity-infstrain/bulk-rheologies/linear-genmaxwell.html: We can add a sub-section here with info from Eric Hetland relating Generalized Maxwell to other viscoelastic models.
- [x] user/governingeqns/elasticity-infstrain/bulk-rheologies/powerlaw.html:  Once we have documented powerlaw_gendb.py we should put a link to it.
- [ ] user/governingeqns/elasticity-infstrain/bulk-rheologies/powerlaw.html:  Bottom of power-law section:  I could explicitly write out the Jacobian terms for G and H.
- [x] user/governingeqns/elasticity-infstrain/bulk-rheologies/alt-formulations.html: I think this section can be removed, as we will probably never use it.
- [x] user/governingeqns/incompressible-elasticity.html: Close parenthesis for pressure in table.
- [x] user/governingeqns/incompressible-elasticity.html: Equation 129, the C_{ijkl} entries should actually be C_{ijkl}^{dev}.
- [x] user/run-pylith/overview.html: Do we mention Gmsh or is that for a future release?
- [x] user/run-pylith/petsc-options.html: Ref for Saad and Schultz.
- [x] user/run-pylith/mesh.html: Gmsh is mentioned here, so should probably be mentioned in previous sections.
- [x] user/run-pylith/utilities.html: ‘bin’ and ‘pyre_doc.py’ in the first paragraph are not formatted correctly in my build.
- [x] user/run-pylith/utilities.html: powerlaw_gendb is missing.
- [x] user/run-pylith/parameter-gui.html: httphttp://127.0.0.1:9000 in section ‘Start the web server’.
- [x] user/run-pylith/troubleshooting.html: Fix heading:  Detected zero pivor in LU factorization
- [x] user/problems/output.html: Close parentheses in first list (progress monitors).
- [x] user/physics/materials/index.html: Should there be a poroelasticity section?

##  Physics Implementations

- [x] user/physics/faults/prescribed-slip.html: Fix refs for Brune and Liu.
- [x] user/components/apps/index.html: Looks like several apps are missing. Only EqInfoApp and PyLithApp are included.
- [x] user/components/bc/AbsorbingDampers.html: Should it look like this?  current value: ‘auxiliary_subfields’, from {file=’/Users/baagaard/software/unix/py39-venv/pylith-debug/lib/python3.9/site-packages/pythia/pyre/inventory/ConfigurableClass.py’, line=26, function=’set’}
This happens for auxiliary_subfields in several components.
- [x] user/components/bc/NeumannTimeDependent.html: Formatting of tangential directions in important box looks messed up.
- [x] user/components/faults/KinSrcBrune.html: Fix ref for Brune.
- [x] user/components/faults/KinSrcLiuCos.html: Fix ref for Liu.
- [x] user/components/materials/index.html:  Do we have both LinearPoroelasticity and Poroelasticity? If so, should there be entries for both under Isotropic… and Rheology…?

**Comment by baagaard-usgs** [comment]
## Won't fix

1. user/install/index.html: We may need to note issues using the Mac binary to install PyLith 2.x if using 12.3 or above (I think that’s the version). - The manual is for v3.0.0, so we don't need to add information about PyLith v2.x.

## Added TODOs

1. user/governingeqns/elasticity-infstrain/bulk-rheologies/linear-genmaxwell.html: We can add a sub-section here with info from Eric Hetland relating Generalized Maxwell to other viscoelastic models.
2. user/governingeqns/elasticity-infstrain/bulk-rheologies/powerlaw.html:  Once we have documented powerlaw_gendb.py we should put a link to it.
3.
