### ISSUE TITLE
Coupling between poroelastic material and standard cohesive faults

### ISSUE THREAD

**Issue by rwalkerlewis** [geodynamics/pylith#498]
## Description

Standard FaultCohesiveKin faults need to be able to be coupled with poroelastic materials.

## Desired Solution

At the moment, a petsc bug is standing in the way.

## Additional context

An example is given in the folder examples/poroelastic_materials_ss-2d in this branch:
https://github.com/rwalkerlewis/pylith/tree/Poroelastic_Material_Standard_Fault

**Comment by baagaard-usgs** [comment]
@rwalkerlewis Please provide detailed instructions for how to run the example and the error message that is generated.

**Comment by rwalkerlewis** [comment]
Running ${TOPSRC_DIR}/pylith/examples/poroelastic_material_ss-2d/pylith step02_coseismic.cfg mat_poroelastic_ss2d.cfg
