### ISSUE TITLE
zenodo doi does not resolve

### ISSUE THREAD

**Issue by ljhwang** [geodynamics/pylith#516]
## URL(s)

[Version v3.0.1 ](https:// .org/record/6667808)10.5281/zenodo.6667808
[Version v3.0.0 ](https://zenodo.org/record/6622161)10.5281/zenodo.6622161

## Description

The correct DOIs for vesion 3.0.1 and 3.0.0  is listed above.

README tags this as: 
   https://doi.org/10.5281/zenodo.6667614
which does not resolve.

**Comment by baagaard-usgs** [comment]
Submitted a support request to remove the duplicate records.
