### ISSUE TITLE
Writing distribution of mesh among processors not implemented in v3.0

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#529]
## Describe the bug

We have not yet implemented writing the distribution of the mesh among processors in the `main` branch.

**Comment by baagaard-usgs** [comment]
@knepley I have this implemented. However, the output includes cells in the overlap. That is, I create a dataset (vector) with N degrees of freedom matching the number of actual cells, but the topology/cells dataset in the output has a size of N+m.

**Comment by knepley** [comment]
@baagaard-usgs  Can we just use -dm_partition_view?

**Comment by baagaard-usgs** [comment]
The switch that I have to write out the partition will write HDF5/Xmf files and follows the file convention naming provided by the problem defaults, so it is consistent with the PyLith user experience.

**Comment by baagaard-usgs** [comment]
Implemented in `baagaard/feature-version-3.0.3`.
