### ISSUE TITLE
Why Pylith randomly kills mpirun in 3D subduction examples?

### ISSUE THREAD

**Issue by sungho91** [geodynamics/pylith#541]
## Describe the bug

Hi all. 
I am using a binarry Pylith 2.2.2 in Ubuntu 22.04 and running ~/bin/pylith-2.2.2-linux-x86_64/src/pylith-2.2.2/examples/3d/subduction$step**.cfg.
I faced some bugs or errors with parallel calculation.

There are no errors for single core calculation (mpirun -np 1 pylith [arguments] or just pylith [arguments]).

For example, when I typed "mpirun -np 2 pylith step01.cfg mat_elastic.cfg or multiple cores".
Initially, mpinemesis(s) corresponding to assigned cores are listed in processes, which can be shown in "top". 
However, some mpinemesis are going to disappear and Pylith is running with fewer cores than the cores I originally commanded.

In my terminal, I can see some error messages. 

***
pylith-2.2.2-linux-x86_64/lib/python2.7/site-packages/pylith/problems/Formulation.py:466:_initialize
 -- implicit(info)
 -- Initializing integrators.
**Fatal error. Calling MPI_Abort() to abort PyLith application.
Traceback (most recent call last):**
***
**IOError: Unable to open file** (truncated file: eof = 729176, sblock->base_addr = 0, stored_eof = 737216)
application called **MPI_Abort(MPI_COMM_WORLD, -1) - process 0**
 >> /pylith-2.2.2-linux-x86_64/lib/python2.7/site-packages/pylith/problems/Formulation.py:475:_initialize
 -- implicit(info)
 -- Initializing constraints.
 >> ~/bin/pylith-2.2.2-linux-x86_64/lib/python2.7/site-packages/pylith/problems/Formulation.py:481:_initialize
 -- implicit(info)
 -- Setting up solution output.
/pylith-2.2.2-linux-x86_64/bin/nemesis: **mpirun: exit 255**
/pylith-2.2.2-linux-x86_64/bin/pylith: /pylith-2.2.2-linux-x86_64/bin/**nemesis: exit 1**

## To Reproduce
Try to parallelly run Pylith 2.2.2 in 3d subduction examples (step01 to step08).
Ex) mpirun -np 2 pylith step01.cfg mat_elastic.cfg 

## Screenshots
![Screenshot from 2022-10-26 20-35-42](https://user-images.githubusercontent.com/40257026/198171163-ba0011f2-6345-4a7d-83e8-bb202318b7d6.png)

## Environment

- OS: [Ubuntu 22.04]
- PyLith version [for example, v2.2.2 Linux binary]

## Additional context

ANY comments are really helpful for me.

Sungho

**Comment by baagaard-usgs** [comment]
When running in parallel if a process detects an error, it will exit. Depending on the MPI implementation and operating system, sometimes other processes do not get notified, so they keep running. The processes that keep running will end up at.a point in the code where they will try to send or receive information from other processes and they will stall. `top` may show CPU usage but the process is not doing any real work.

So it looks like you are running into an error associated with output and PyLith aborts, but not cleanly and some processes try to keep running. I will try to replicate your run and see if I can identify the issue.

**Comment by sungho91** [comment]
@baagaard-usgs 

Thank you for your comment.

My observation shows differences from what you mentioned. 

First of all, some survived processes on **top** have some loads in CPU and memory too. 
Furthermore, those processes are running till the end of simulation and then writing outputs.
Those outputs seem identical to outputs from single-core calculation (below picture shows this).

![step01](https://user-images.githubusercontent.com/40257026/198306330-a8652e06-da00-4dbf-84bb-ba47c949d179.png)

While my terminal for the multi-core calculation shows "mpirun: exit 255 and nemesis: exit 1" at the end. It was not shown in the single-core calculation.

I think the survived processes seemed correctly finished. 

Thus, single-core calculation could be a candidate for a solution to resolve this issue or multi-core calculation is also okay even though my terminal shows some errors. 

However, I am not sure I can trust multi-core calculation when I need multi-core calculation for my own problem, which actually shows this same issue. 

So, I hope we resolve this issue.

**Comment by baagaard-usgs** [comment]
Sorry, I missed the details of how you are trying to run in parallel. The problem is that to run PyLith in parallel, you do NOT use `mpiexec -n NPROCS pylith ARGS`, you use `pylith --nodes=NPROCS ARGS`. PyLith can launch MPI jobs via a variety of methods, including submitting jobs to batch systems on clusters. On a desktop, PyLith will start the job in parallel using mpirun. In fact, it will do some validation of the input before launching in parallel.

When you do `mpiexec -n PROCS pylith ARGS`, you are simply starting NPROCS serial runs of PyLith. They will conflict with each other when they try to open and write output files with the same names and some will abort.

**Comment by baagaard-usgs** [comment]
Looking through manual, I realize how to run in parallel on a desktop is not discussed sufficiently. I will add this to the manual. See #542

**Comment by sungho91** [comment]
@baagaard-usgs 

Did you mean I made serial runs but not a parallel run? If it is correct, now I understood why Pylith was conflicted.
However, still, I don't understand how can I submit my job to my desktop.

What do I have to write a command line instead of "mpirun -np nodes program <args>"?
Or, do I have to use a job scheduler?

**Comment by baagaard-usgs** [comment]
Running `mpiexec -n NPROCS pylith ARGS` will run NPROCS serial runs simultaneously, all trying to do the exact same thing.

As I mentioned above, to run in parallel with NPROCS processes on a desktop, simply use `pylith --nodes=NPROCS ARGS`. That is, to run pylith in parallel on a desktop, all you need to do is add the `--nodes=NPROCS` argument to your normal command line arguments. PyLith will do everything necessary to start the job.

**Comment by sungho91** [comment]
@baagaard-usgs 

I got it! It is working now.
Thank you so much.
