### ISSUE TITLE
Question: Stress wave induced earthquakes

### ISSUE THREAD

**Issue by FURUNZ** [geodynamics/pylith#545]
## Description

I want to study stress wave induced earthquakes. Is it feasible to use pylith？How do you apply stress waves to real boundary conditions in pylith？I need a fault under critical failure conditions. How do I set the material parameters？

**Comment by baagaard-usgs** [comment]
I assume you are asking whether you can compute slip on a fault with friction from a stress wave propagating through the domain. This is possible in PyLith v2.2.2; PyLith v3 does not yet have fault friction. For a propagating stress wave, you will need to use the explicit formulation, which includes inertia. You can use the Neumann boundary condition to impose deformation on the boundary that will result in a propagating wave that induces tractions on the fault. See the PyLith manual, especially the examples, for how to set material parameters.

If you have further questions, we recommend using the [CIG community forum](https://community.geodynamics.org/c/pylith/29). Please provide a detailed description of the boundary value problem you are trying to solve along with a diagram.

**Comment by baagaard-usgs** [comment]
I am closing this issue because there do not appear to be any more questions.
