### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by yuxin0909** [geodynamics/pylith#564]
I want to ask how pylith realizes the conversion of wgs84 coordinates to utm. In the 3d subduction problem, given the latitude and longitude, the displacement corresponding to the utm coordinate point can be output. I want to know how to obtain the latitude and longitude utm coordinates of other points from the known point as the origin.

**Comment by knepley** [comment]
We use the `proj` library

**Comment by baagaard-usgs** [comment]
Here is the [Proj](https://proj.org/) website with complete documentation.
