### ISSUE TITLE
Error when trying to use fault surface divided into parts

### ISSUE THREAD

**Issue by quanzhenlaozu** [geodynamics/pylith#656]
Hello, I will divide the slab into three parts, with the node set being fault_ slab1, fault_ Slabtop2, fault_ slab3, fault_ slabbot1, fault_ slabbot2, fault_ Slabbot3, each part is set with a displacement, but an error occurred during runtime, 'Error occurred while adjusting topology to create cohesive cells for fault' fault_slabbot2 ',Error in topology of mesh associated with symmetry of advertising information Can't it be set like this?

**Comment by knepley** [comment]
I think this is 2.2. This error occurs when there is a problem inserting cohesive cells. This can happen, for instance, when all vertices of a cell are on the same fault. Does this happen?

**Comment by quanzhenlaozu** [comment]
Yes，this is 2.2.I also just split slab into three parts, like the image below.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geodynamics/pylith"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月27日(星期三) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [geodynamics/pylith] [REPLACE THIS WITH AN APPROPRIATE TITLE FOR YOUR BUG REPORT] (Issue #656)





 
I think this is 2.2. This error occurs when there is a problem inserting cohesive cells. This can happen, for instance, when all vertices of a cell are on the same fault. Does this happen?

**Comment by baagaard-usgs** [comment]
You cannot break a fault surface into separate pieces that touch without inserting a buried edge between the pieces. Inserting the buried edges allows the algorithm that inserts the cohesive cells to work, but it is almost certainly NOT what you want because it will pin the slip to zero along the buried edges. The workaround is to use a single fault surface. If you provide a diagram of the boundary value problem you are trying to solve, then we can provide guidance on how to solve it using PyLith.

**Comment by quanzhenlaozu** [comment]
Thank you.I want to divide the slab_top into three parts, each with different displacement settings. The following two pictures are my model and questions.The first image shows the model without grid, and the second image shows the model after grid establishment.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "geodynamics/pylith"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月27日(星期三) 晚上10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [geodynamics/pylith] Error when trying to use fault surface divided into parts (Issue #656)





 
You cannot break a fault surface into separate pieces that touch without inserting a buried edge between the pieces. Inserting the buried edges allows the algorithm that inserts the cohesive cells to work, but it is almost certainly NOT what you want because it will pin the slip to zero along the buried edges. The workaround is to use a single fault surface. If you provide a diagram of the boundary value problem you are trying to solve, then we can provide guidance on how to solve it using PyLith.

**Comment by baagaard-usgs** [comment]
None of your images are showing up in the GitHub issues. Please upload them through the web browser interface.

You can use a spatial database to specify variations in slip over a fault surface. See the examples.

**Comment by quanzhenlaozu** [comment]
Sorry, I seem to understand how to handle it, and I can set up different in the database. Thank you very much for your answer
