### ISSUE TITLE
Error about value not found at location for spatial database

### ISSUE THREAD

**Issue by quanzhenlaozu** [geodynamics/pylith#657]
I use pylith 2.2.2. I want to divide the slab into three parts, with different sliding displacements. But after I edit a spatial database, running the code makes an error. Tip the displacement of the point on the surface cannot be found.“ RuntimeError: Could not find slip rate at (  -945733  1.04754e+06  -5967.39) using spatial database 'Slab top slip rate.” The following two diagrams are the Settings of my model and spatial database. 
![IMG_0060](https://github.com/geodynamics/pylith/assets/120887835/6db2b98b-c618-434d-bcd4-b29b92936c2c)
<img width="262" alt="71e6d55b42dfc4ef0d2d0e7a722b50d4" src="https://github.com/geodynamics/pylith/assets/120887835/4217b63a-8e28-4e86-9eae-4a1268234b01">

**Comment by baagaard-usgs** [comment]
Your spatial database provides the coordinates in km. Did you specify a scaling factor of 1000 for a Cartesian coordinate system like in the following example?

```
  cs-data = cartesian {
    to-meters = 1000.0
    space-dim = 3
  }
```

See the [SimpleGridDB](https://spatialdata.readthedocs.io/en/latest/user/spatialdb/simplegriddb.html) and [CSCart](https://spatialdata.readthedocs.io/en/latest/user/coordsys.html#cscart) documentation for more information.

When asking for help, please provide entire files and output (you can attach or copy and paste into the issue) as described in the [Getting Help and Reporting Bugs section of the PyLith manual](https://pylith.readthedocs.io/en/latest/user/intro/getting-help.html). In most cases, we can provide better answers to questions when we have more information.

**Comment by quanzhenlaozu** [comment]
Thank you. The following two pictures are my spatial database and the support results after operation.
<img width="347" alt="IMG_3038" src="https://github.com/geodynamics/pylith/assets/120887835/14c9f4cd-e03f-49c0-afb9-ea8eff9450f2">
<img width="431" alt="111(1)" src="https://github.com/geodynamics/pylith/assets/120887835/60c6aff5-fa26-4379-b383-225ddfcc6ab9">

**Comment by quanzhenlaozu** [comment]
I change unit=m to unit=km, and it can run successfully. Thank you for your answer！
