### ISSUE TITLE
Negative porosities when using poroelastic material with state variables

### ISSUE THREAD

**Issue by danieldouglas92** [geodynamics/pylith#658]
## Describe the bug

When using poroelasticity and state variables, the porosity field can develop

## To Reproduce

**PETSc branch**:  knepley/pylith
**PyLith fork**: https://github.com/baagaard-usgs/pylith.git
**PyLith branch**: baagaard/example-poroelasticity-statevars

Steps to reproduce the behavior.

pylith step01_elastic_bending.cfg

## Expected behavior

The porosity as a physical parameter should not be negative, 

## Screenshots

<img width="6
[variable_permeability.txt](https://github.com/geodynamics/pylith/files/12769160/variable_permeability.txt)
42" alt="image" src="https://github.com/geodynamics/pylith/assets/55814099/82ef9f8f-6aaf-4f45-8a33-3f43d786defe">

## Environment

Please provide the following information:

- OS: Mac Monterey v 12.0.1 M1 Max 
- PyLith version v3

## Additional context

[step01_elastic_bending.txt](https://github.com/geodynamics/pylith/files/12769169/step01_elastic_bending.txt)
[variable_permeability.txt](https://github.com/geodynamics/pylith/files/12769173/variable_permeability.txt)
[pylithapp copy.txt](https://github.com/geodynamics/pylith/files/12769175/pylithapp.copy.txt)
[top_boundary.txt](https://github.com/geodynamics/pylith/files/12769237/top_boundary.txt)

**Comment by knepley** [comment]
Is the porosity a function of other variables? If so, which ones and how are they updated? Pointing me to code is fine.

**Comment by baagaard-usgs** [comment]
The update of the porosity (plane strain) is in [`fekernels/IsotropicLinearPoroelasticity.hh`](https://github.com/geodynamics/pylith/blob/main/libsrc/pylith/fekernels/IsotropicLinearPoroelasticity.hh#L2488).

**Comment by danieldouglas92** [comment]
I'm not 100% sure if this is the place but I see it in IsotropicLinearPoroelasticity.hh at line 2488

**Comment by knepley** [comment]
We should put in an assert there for negative porosity, or a clamp

**Comment by danieldouglas92** [comment]
The porosity should only be between 0 and 1, so I think a clamp makes sense!

**Comment by rwalkerlewis** [comment]
I agree.

**Comment by baagaard-usgs** [comment]
Fixed in branch `example-poroelasticity-statevars` in `https://github.com/baagaard-usgs/pylith.git`.
