### ISSUE TITLE
Preconditioner for 6-field poroelasticity formulation

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#662]
## Description

For poroelasticity the default preconditioners are LU when running in serial and ML when running in parallel. When using the 6-field poroelasticity formulation (used when porosity evolves as a state variable), ML is a terrible preconditioner.

@knepley What is a reasonable preconditioner for poroelasticity problems, especially when we have the 6-field formulation?

**Comment by knepley** [comment]
So this is displacement, Lagrange multiplier, pore pressure, trace strain, porosity, and what else?

**Comment by danieldouglas92** [comment]
This is when using SolnDispPresTracStrainVelPdotTdot (no Lagrange)

**Comment by baagaard-usgs** [comment]
Displacement, trace strain, fluid pressure, velocity, time derivative of trace strain, and time derivative of fluid pressure. We don't really need velocity (not used to update porosity). The second set of fields are just the time derivative of the first set.

**Comment by knepley** [comment]
Okay, the time derivative parts are likely easy (just mass matrices), so the hard part is the poroelastic block. We should write out the Jacobian, but I think if we order time derivatives first, it is block upper triangular, so if we do a block solve with PCFIELDSPLIT, it will be exact if we solve the two blocks exactly. You can do the time derivative block with just ILU(0) or even Jacobi. The poroelastic block should probably be broken down again, but lets start with LU.

**Comment by baagaard-usgs** [comment]
## Preconditioner for poroelasticity

Need to update default solver settings for quasi-static poroelasticity to the following:

```
[pylithapp.petsc]
pc_type = fieldsplit
pc_fieldsplit_type = multiplicative
pc_fieldsplit_0_fields = 2
pc_fieldsplit_1_fields = 1
pc_fieldsplit_2_fields = 0
fieldsplit_trace_strain_pc_type = ilu
fieldsplit_pressure_pc_type = ilu
fieldsplit_displacement_pc_type = lu
```

## Preconditioner for poroelasticity with state variables

Need to update default solver settings for quasi-static poroelasticity with state variables to the following:

```
[pylithapp.petsc]
pc_type = fieldsplit
pc_fieldsplit_type = multiplicative
pc_fieldsplit_0_fields = 2
pc_fieldsplit_1_fields = 1
pc_fieldsplit_2_fields = 0
fieldsplit_trace_strain_pc_type = ilu
fieldsplit_pressure_pc_type = ilu
fieldsplit_displacement_pc_type = lu

pc_fieldsplit_3_fields = 3
pc_fieldsplit_4_fields = 4
pc_fieldsplit_5_fields = 5
fieldsplit_velocity_pc_type = ilu
fieldsplit_pressure_t_pc_type = ilu
fieldsplit_trace_strain_t_pc_type = ilu
```

I suspect the Jacobian is wrong for in this case, because magma-2d/step02-inflation-statevars fails to converge at around time step 31.

- [ ] Update default solver settings for poroelasticity
- [ ] Update documentation with case of quasi-static poroelasticity with state variables
- [ ] Check Jacobian using simple problem
- [ ] Remove trace_strain_t field (not used in updating state variables)

**Comment by baagaard-usgs** [comment]
@knepley The settings above work well for serial runs. What should we use when running in parallel? Instead of LU for the elasticity part, I am guessing we should use ML. What is a good substitute for ILU when running in parallel?

**Comment by knepley** [comment]
Yes, ML for elasticity, and I think PBJACOBI/ILU should work for the mass matrices `fieldsplit_pressure_pc_type bjacobi sub_fieldsplit_pressure_pc_type ilu` I think, but I forget where sub gets inserted.

**Comment by baagaard-usgs** [comment]
@knepley Using pbjacobi instead of ILU increases the number of linear iterations for the first time step from 35 (45 s for 50 time steps) to 272 (59 s for 50 time steps), both with 1 process. So.. the iterations are faster but more are required. Is that to be expected?

**Comment by baagaard-usgs** [comment]
@knepley Here is a more thorough evaluation of the effect of changing the preconditioner. 

```
(trace strain, pressure, displacement): # iterations for first linear solve
(ilu, ilu, lu): 35
(ilu, ilu, ml): 168
(pbjacobi, pbjacobi, ml): 272
(pbjacobi, pbjacobi, lu): 225
```

Is it worth doing more fine tuning or is this increase expected in going from ilu -> pbjacobi and lu -> ml?

**Comment by baagaard-usgs** [comment]
The solution is to use `bjacobi` instead of `pbjacobi`, which matches `ilu` in serial. In parallel, set the displacement KSP type to `gmres`.
