### ISSUE TITLE
Segmentation fault in DMCreateMatrix_Plex()

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#684]
## Describe the bug

Segmentation fault in `DMCreateMatrix_Plex()` at `plex.c:2857`

```
pblocks[0]       = PetscAbs(pblocks[0]);
```

when `pblocks` is nullptr.

##

This error shows up in the full-scale tests.

**PETSc branch**: `knepley/feature-partitioner-edge-weights`
**PyLith fork**: `https://github.com/baagaard-usgs/pylith.git`
**PyLith branch**:  `improve-elasticity-fault-pc`

```
cd $BUILD/tests/fullscale/cornercases/nofaults-2d
pylith dofconstrained.cfg dofconstrained_quad.cfg
```

**Comment by knepley** [comment]
Yep, I fixed that this morning.

**Comment by knepley** [comment]
It is in the same branch. I am in the process of getting it merged.
