### ISSUE TITLE
Variable point block Jacobian preconditioner for fault fails with basis order 2

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#701]
## Describe the bug

The variable point block Jacobi preconditioner that is the default for elasticity + fault fails for basis order 2. 

@knepley will check PETSc tests for whether the section looks to be reordered and blocks created correctly for basis order 2.

## To Reproduce

@baagaard will setup a test case for verification with PyLith.

**PETSc branch**: `[REPLACE WITH PETSC_BRANCH]`
**PyLith fork**: `[REPLACE WITH URL OF YOUR PYLITH FORK]`
**PyLith branch**: `[REPLACE WITH PYLITH BRANCH]`

**Comment by knepley** [comment]
@baagaard-usgs I think this should now work with `knepley/fix-plex-cohesive-blocks`

**Comment by baagaard-usgs** [comment]
FIxed in PETSc branch knepley/fix-plex-cohesive-blocks via [MR 7586](https://gitlab.com/petsc/petsc/-/merge_requests/7586).
