### ISSUE TITLE
Permission Issues with PyLith 4.0 on M1 MacBook

### ISSUE THREAD

**Issue by sungho91** [geodynamics/pylith#706]
## Describe the issue

Hi, I tried to run the binary PyLith 4.0 on my MacBook (M1 processor), but my laptop recognized PyLith as malicious software. I gave permission through Security, but an endless stream of dependencies sequentially required permission checks. I was just wondering how you all run PyLith on Apple machines.

Best,

Sungho

**Comment by baagaard-usgs** [comment]
We strongly recommend using `curl` to download the binary package to bypass Apple quarantine flags. Refer to the [installation instructions](https://pylith.readthedocs.io/en/latest/user/install/index.html#installation-of-binary-executable) in the PyLith manual and, in particular, the `Tip` box that discusses the macOS quarantine flags.

**Comment by sungho91** [comment]
@baagaard-usgs, thank you so much.

Pylith on my laptop is working now.

**Comment by priyankamishr** [comment]
curl -L -O https://github.com/geodynamics/pylith/releases/download/v5.0.0/pylith-5.0.0-macOS-10.15-x86_64.tar.gz, this link is not active. Kindly share the updated link to download the latest release.

**Comment by baagaard-usgs** [comment]
Version 5.0.0 has not been released. https://pylith.readthedocs.io/en/latest/ corresponds to the current `main` branch of the code, which is the development version. We anticipate completing this release in the next month. For the current release (v4.2.0) use the link https://pylith.readthedocs.io/en/stable/. In the lower right corner, you can switch between releases. We will update the links to the documentation to use the `stable` URL to avoid confusion.
