### ISSUE TITLE
The quadrature order *must* the same for all solution and auxiliary subfields?

### ISSUE THREAD

**Issue by sungho91** [geodynamics/pylith#708]
## Description

Hi,

I've seen some descriptions in examples stating that `the quadrature order must be the same for all solution and auxiliary subfields` because PyLith will verify that this requirement is met (Pylith 4.0.0).

I was just wondering if the quadrature order should be at least 1 order greater than the basis function to achieve accurate integration?

Best,
Sungho

**Comment by baagaard-usgs** [comment]
For accurate integration, the quadrature _order_ need only match the basis order. In 1D the number of _points_ for the Gauss quadrature is 1 greater than the order. If all solution fields have the same basis order, then the default quadrature order, which matches the basis order, should work. If the solution fields have different basis orders, then the quadrature order should be set to greatest basis order.

**Comment by sungho91** [comment]
@baagaard-usgs, I see. So, if we choose the same order, quadrature for basis k should have k+1 points for integration, right?

**Comment by baagaard-usgs** [comment]
In 1D with Gauss quadrature, yes the quadrature for basis order k will have k+1 points. In 2D and 3D it is more complicated. We are also not limited to Gauss quadrature.

**Comment by sungho91** [comment]
@baagaard-usgs, thank you for clarifying that. I was presuming a 1D case because I remembered that the number of quadrature points should be greater than the order of the basis function from my old memory. Yes, in 2d and 3d, it should be complicated.
