### ISSUE TITLE
`DMProjectFunctionLabelLocal()` isn't setting values

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#71]
PETSc branch: `knepley/pylith`
PyLith branch: `baagaard/feature-initial-conditions`

When using `DMProjectFunctionLabelLocal()` to set values for initial conditions over a patch of the domain, no values are set.

I have verified that the value of the label has points associated with it. It looks like the intersection between the label pointIS and the heightIS is empty. The pointIS should contain vertices.

## Reproduce

Apply attached patch to workaround some DM issues.
[patch.gz](https://github.com/geodynamics/pylith/files/3040929/patch.gz)

```
cd tests_auto/linearelasticity/faults
pylith twoblocks_quad.cfg
```

Expect initial conditions to set solution field to (0,+1) on +x side of the fault and (0,-1) on the -x side of the fault.

**Comment by baagaard-usgs** [comment]
I think the function could be assuming that the label is for a boundary rather than a patch of the domain as this function was originally setup to set boundary condition values.

**Comment by knepley** [comment]
Right. The label needs to have cells in it in order for Project*() to work. I was thinking you were going to use the material labels.

**Comment by baagaard-usgs** [comment]
We could use material labels to define these patches, but there is no direct relationship between a material (governing equations and properties) and the patches over which we want to define the solution for initial conditions. For example, a homogeneous half space with a fault in it is one material, but we would generally want two patches for initial conditions.

For now, I can use material labels, but we should think if there is a better way create the appropriate label. I have opened Issue https://github.com/geodynamics/pylith/issues/74 for a longer term, more robust fix.
