### ISSUE TITLE
Quick typo fix

### ISSUE THREAD

**Issue by keelwilde** [geodynamics/pylith#742]
## URL(s)

<https://pylith.readthedocs.io/en/v4.0.0/user/install/index.html>

Section: Verifying PyLith is Installed Correctly

## Description

In the Code Example box, `$ pylilth step01_axialdisp.cfg` should be changed to `$ pylith step01_axialdisp.cfg`

**Comment by baagaard-usgs** [comment]
Thanks! This fix will appear in the 4.1.1 release and will go into the online version of the manually later today.
