### ISSUE TITLE
Initial conditions for Lagrange multipliers

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#75]
The current implementation of `DMProjectionFunctionLabelLocal()` does not work for setting the initial conditions for Lagrange miultipliers associated with the fault.

When DMProjectionFunctionLabelLocal() tries to set the values for the patch corresponding to label for the cohesive cells:

1. It tries to set values for the displacement field (it should skip these).

2. It does not try to set the values for the Lagrange multiplier.

**Comment by knepley** [comment]
Can you give me the URL to the place in the code where it is called? This would actually be awesome for all these bug reports.

**Comment by baagaard-usgs** [comment]
https://github.com/geodynamics/pylith/blob/baagaard/feature-initial-conditions/libsrc/pylith/topology/FieldQuery.cc#L224

**Comment by knepley** [comment]
You have "0, NULL" for the field argument. It sounds like you want to explicitly give the field that should be set here.

**Comment by baagaard-usgs** [comment]
Need to add ability to specify only a subset of fields in the initial conditions. This is important for specifying the initial fault tractions using the cohesive cells, because the dispalcement field etc should be specified by the bulk cells not the cohesive cells.

Should add list of fields to InitialCondition, since it seems like it would be appropriate for all implementations.

**Comment by baagaard-usgs** [comment]
**PyLith branch**: `baagaard/feature-initial-conditions-fault`

Implementing ability to specify initial conditions on a per field basis.
