### ISSUE TITLE
Fault orientation is inconsistent again (v4.1.2 okay, but not v4.1.3 or later)

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#771]
## Describe the bug

The fault orientation bug we fixed in v4.1.2 has returned. I appears in v4.1.3 and the current PyLith main. I don't know if we lost the "correct" code or we introduced another bug that messes up the fault orientation.

See #750

**Comment by baagaard-usgs** [comment]
@knepley It looks to me like `knepley/fix-orientation-input` was never merged into PETSc main. Can you confirm?

**Comment by knepley** [comment]
Thats right. I am running the CI now.
