### ISSUE TITLE
Does PyLith support simulation features related to spontaneous slip?

### ISSUE THREAD

**Issue by Ultrafollow** [geodynamics/pylith#789]
Dear Sir，

I would like to inquire if PyLith is capable of simulating the scenario depicted in the figure—strike-slip faulting that is caused by the displacement rate applied at the model boundaries, leading to fault slip, and then certain areas are squeezed and uplifted due to adjacent boundaries being set to zero displacement.

Thank you.
best regards.
![6b3426584e51335551489a4fc83c7f6](https://github.com/user-attachments/assets/9300d31d-91b2-48c2-890f-eb890a5bca1b)

**Comment by baagaard-usgs** [comment]
Spontaneous rupture (fault friction) is available in PyLith v2. Refer to the PyLith v2.2.2 manual available with the [version 2.2.2 release](https://github.com/geodynamics/pylith/releases/tag/v2.2.2). Re-implementing spontaneous rupture using the revised formulation for governing equations in version 3.0 and later is still in progress.

**Comment by Ultrafollow** [comment]
Thank you @baagaard-usgs  for your support！
