### ISSUE TITLE
Project of solution to material subDM passes wrong values to project function

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#89]
Calling `DMProjectFieldLocal()` to compute a derived field from the solution field gives erroneous results. Within the PetscPointFun, at many points the solution does not match the coordinates. The solution values do match the ones for some other points.

# Test case

**PyLith branch**: baagaard/feature-derived-field

```
cd tests_auto/linearelasticity/nofaults
pylith axialdisp.cfg
```

Look at debugging output written to stdout.

**Comment by knepley** [comment]
I believe the problem is that we require the aux mesh to be a boundary before we do lookup. I need to make a table of all the possibilities because now we might need more information than just having a subpointMap. When both meshes have a subpointMap, we do not want to map since we assume they are the same submesh (if not I guess we could map the point to the assumed original mesh and then back down).

**Comment by baagaard-usgs** [comment]
Here is a table of all of the PyLith uses cases for `DMProjectFieldLocal()`:

* **subdomain**: Subset of domain (e.g., material); mesh has same dimension as domain
* **boundary**: External boundary of domain; mesh has dimension one lower than domain
* **interface**: Internal interface of domain; mesh has dimension one lower then domain

| Input vector | Auxiliary vector | Output vector | Purpose | Status |
| ------ | ----- | ----- | ---- | ---- |
| domain | subdomain | subdomain | Compute fields derived from solution and subdomain auxiliary field (e.g., stress, strain) | Not working |
| domain | boundary | boundary | Compute fields derived from solution and boundary auxiliary field  | ?? |
| domain | boundary | domain | Set Dirichlet BC | OK |
| interface | interface | interface | Compute prescribed slip from slip time function parameters | ?? |
| domain | n/a | domain | Reduce basis order | Not working |
| domain | n/a | boundary | Reduce basis order | Not working |
| domain | n/a | subdomain | Reduce basis order | ?? |
| domain | n/a | interface | Reduce basis order | ?? |
| boundary | n/a | boundary | Reduce basis order | ?? |
| subdomain | n/a | subdomain | Reduce basis order | ?? |
| interface | n/a | interface | Reduce basis order | ?? |
| subdomain | subdomain + domain | subdomain | Updating state variables | Should be working; no test |

**Comment by knepley** [comment]
The input and output vector must come from the same space, only the aux vector is allowed to come from a different space, so some combinations will not work. For instance, in the first row, you would need to use subdomain for the input+output, and full domain for the aux.

**Comment by baagaard-usgs** [comment]
I think I got confused with the use of "auxiliary", which has a different meaning than the "auxiliary" field in our integrators, etc.

I switched things so that the subdomain auxiliary field is the input vector, the solution over the domain is the auxiliary vector, and the subdomain derived field is the output vector. I still run into a problem, because my output vector has 2 fields while my input vector has 3 fields. It looks like the DMProjectFieldLocal() function assumes the input and output vectors have the same number of fields. Am I right? If so, can we relax this assumption?

It seems like we should be able to unpack each field (input, auxiliary, output) with each having a different number of fields, and apply functions equal to the number of fields in the output vector.

**Comment by knepley** [comment]
We cannot relax the assumption about matching layouts because only 1 DM comes in, so it is used to layout both input and output vectors. You could, of course, take 2 DMs but this would make everything much more complicated (I think). I think the easiest way to do what you want is to project the vector with nothing in the fields you do not care about and then use CreateSubDM() to extract the fields you want.

**Comment by baagaard-usgs** [comment]
I can come up with a workaround in the short term. However, if this is much, much more complicated to allow difference numbers of fields in the input and output vectors, then the design is not very good. I think it is reasonable to require the same basis and quadrature order, but the number of fields shouldn't have to be the same for the input and output vectors.

**Comment by baagaard-usgs** [comment]
Here is a CORRECTED table of all of the PyLith uses cases for `DMProjectFieldLocal()`:

* **subdomain**: Subset of domain (e.g., material); mesh has same dimension as domain
* **boundary**: External boundary of domain; mesh has dimension one lower than domain
* **interface**: Internal interface of domain; mesh has dimension one lower then domain

| Input vector | Auxiliary vector | Output vector | Purpose | Status |
| ------ | ----- | ----- | ---- | ---- |
| subdomain | domain | subdomain | Compute fields derived from solution and subdomain auxiliary field (e.g., stress, strain) | Not working; see Note 1 |
| boundary | domain | boundary | Compute fields derived from solution and boundary auxiliary field  | ?? |
| domain | boundary | domain | Set Dirichlet BC | OK |
| interface | interface | interface | Compute prescribed slip from slip time function parameters | Should work; no test |
| n/a (Note 2) | domain | domain | Reduce basis order | OK |
| n/a (Note 2) | domain | boundary | Reduce basis order | ?? |
| n/a (Note 2) | domain | subdomain | Reduce basis order | Not working; see Note 1 |
| n/a (Note 2) | domain | interface | Reduce basis order | ?? |
| n/a (Note 2) | subdomain | subdomain | Reduce basis order | Should work; no test |
| n/a (Note 2) | interface | interface | Reduce basis order | Should work; no test |
| subdomain | subdomain + domain | subdomain | Updating state variables | Should work; no test |

**Note 1**: Works for subdomains with cells 0-N. Looks like projection does not account for subpoint map associated with subdomain.

**Note 2**: For reducing basis order, the field with the original basis is the auxiliary vector and the field with the reduced basis is the output vector, which we also use as the input vector.
